name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  main:
    name: Build, Validate, and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: spec.bs
          TOOLCHAIN: bikeshed
          GH_PAGES_BRANCH: gh-pages
          BUILD_FAIL_ON: everything
          VALIDATE_LINKS: true
